In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm
import bar_chart_race as bcr
import warnings
from ydata_profiling import ProfileReport

warnings.filterwarnings("ignore")

In [13]:
prof = ProfileReport(x)
prof.to_file(output_file='output.html')

Summarize dataset: 100%|██████████| 31/31 [00:03<00:00,  8.28it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:08<00:00,  8.37s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.04s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 225.19it/s]

In [2]:
x = pd.read_csv("./IPLMatches.csv")

In [3]:
x

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [4]:
#Toss winners 
x['player_of_match'].value_counts()

player_of_match
AB de Villiers    23
CH Gayle          22
RG Sharma         18
DA Warner         17
MS Dhoni          17
                  ..
S Anirudha         1
M Kartik           1
R McLaren          1
RJ Harris          1
PJ Cummins         1
Name: count, Length: 233, dtype: int64

In [5]:
players=list(x['player_of_match'].unique())
len(players)

234

In [6]:
#Making a new Dataset which is required for the bar chart race
data=np.zeros((816,len(players)))
new_x=pd.DataFrame(data,index=x['date'],columns=players)
new_x

,BB McCullum,MEK Hussey,MF Maharoof,MV Boucher,DJ Hussey,SR Watson,V Sehwag,ML Hayden,YK Pathan,KC Sangakkara,...,Shubman Gill,SO Hetmyer,CV Varun,CJ Jordan,Shivam Mavi,A Nortje,RD Gaikwad,R Tewatia,PK Garg,PJ Cummins
date,,,,,,,,,,,,,,,,,,,,,
2008-04-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-11-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-11-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-11-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-11-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
# Sample Dictionary which we will use in the new Dataset.
players_won={}
for player in players:
    players_won[player]=0
players_won

{'BB McCullum': 0,
 'MEK Hussey': 0,
 'MF Maharoof': 0,
 'MV Boucher': 0,
 'DJ Hussey': 0,
 'SR Watson': 0,
 'V Sehwag': 0,
 'ML Hayden': 0,
 'YK Pathan': 0,
 'KC Sangakkara': 0,
 'JDP Oram': 0,
 'AC Gilchrist': 0,
 'SM Katich': 0,
 'MS Dhoni': 0,
 'ST Jayasuriya': 0,
 'GD McGrath': 0,
 'SE Marsh': 0,
 'SA Asnodkar': 0,
 'R Vinay Kumar': 0,
 'IK Pathan': 0,
 'SM Pollock': 0,
 'Sohail Tanvir': 0,
 'S Sreesanth': 0,
 'A Nehra': 0,
 'SC Ganguly': 0,
 'CRD Fernando': 0,
 'L Balaji': 0,
 'Shoaib Akhtar': 0,
 'A Mishra': 0,
 'DPMD Jayawardene': 0,
 'GC Smith': 0,
 'DJ Bravo': 0,
 'M Ntini': 0,
 'SP Goswami': 0,
 'A Kumble': 0,
 'KD Karthik': 0,
 'JA Morkel': 0,
 'P Kumar': 0,
 'Umar Gul': 0,
 'SK Raina': 0,
 'SR Tendulkar': 0,
 'R Dravid': 0,
 'DL Vettori': 0,
 'RP Singh': 0,
 'M Muralitharan': 0,
 'CH Gayle': 0,
 'AB de Villiers': 0,
 'RS Bopara': 0,
 'PP Ojha': 0,
 'TM Dilshan': 0,
 'HH Gibbs': 0,
 'DP Nannes': 0,
 'JP Duminy': 0,
 'Yuvraj Singh': 0,
 'SB Jakati': 0,
 'JH Kallis': 0,
 'G Gambhir': 0,
 'RG Sharma': 0,
 'A Singh': 0,
 'S Badrinath': 0,
 'DR Smith': 0,
 'LRPL Taylor': 0,
 'Harbhajan Singh': 0,
 'R Bhatia': 0,
 'SK Warne': 0,
 'B Lee': 0,
 'BJ Hodge': 0,
 'LR Shukla': 0,
 'MK Pandey': 0,
 'AD Mathews': 0,
 'MK Tiwary': 0,
 'WPUJC Vaas': 0,
 'A Symonds': 0,
 'AA Jhunjhunwala': 0,
 'J Theron': 0,
 'RV Uthappa': 0,
 'AC Voges': 0,
 'KM Jadhav': 0,
 'NV Ojha': 0,
 'DA Warner': 0,
 'SL Malinga': 0,
 'M Vijay': 0,
 'KP Pietersen': 0,
 'AT Rayudu': 0,
 'PD Collingwood': 0,
 'MJ Lumb': 0,
 'TL Suman': 0,
 'RJ Harris': 0,
 'PP Chawla': 0,
 'Harmeet Singh': 0,
 'KA Pollard': 0,
 'R Ashwin': 0,
 'R McLaren': 0,
 'JD Unadkat': 0,
 'M Kartik': 0,
 'DE Bollinger': 0,
 'S Anirudha': 0,
 'SK Trivedi': 0,
 'SB Wagh': 0,
 'PC Valthaty': 0,
 'MD Mishra': 0,
 'DW Steyn': 0,
 'S Sohal': 0,
 'MM Patel': 0,
 'V Kohli': 0,
 'I Sharma': 0,
 'J Botha': 0,
 'Iqbal Abdulla': 0,
 'P Parameswaran': 0,
 'R Sharma': 0,
 'MR Marsh': 0,
 'BA Bhatt': 0,
 'S Aravind': 0,
 'WP Saha': 0,
 'S Dhawan': 0,
 nan: 0,
 'JEC Franklin': 0,
 'RE Levi': 0,
 'SPD Smith': 0,
 'AM Rahane': 0,
 'RA Jadeja': 0,
 'MN Samuels': 0,
 'M Morkel': 0,
 'F du Plessis': 0,
 'AD Mascarenhas': 0,
 'Shakib Al Hasan': 0,
 'JD Ryder': 0,
 'SP Narine': 0,
 'S Nadeem': 0,
 'KMDN Kulasekara': 0,
 'CL White': 0,
 'Mandeep Singh': 0,
 'P Negi': 0,
 'Azhar Mahmood': 0,
 'BW Hilfenhaus': 0,
 'A Chandila': 0,
 'UT Yadav': 0,
 'MS Bisla': 0,
 'M Vohra': 0,
 'GH Vihari': 0,
 'AJ Finch': 0,
 'JP Faulkner': 0,
 'MS Gony': 0,
 'DA Miller': 0,
 'SV Samson': 0,
 'DJG Sammy': 0,
 'MG Johnson': 0,
 'KK Cooper': 0,
 'PA Patel': 0,
 'AP Tare': 0,
 'LJ Wright': 0,
 'YS Chahal': 0,
 'GJ Maxwell': 0,
 'CA Lynn': 0,
 'MM Sharma': 0,
 'PV Tambe': 0,
 'Sandeep Sharma': 0,
 'B Kumar': 0,
 'CJ Anderson': 0,
 'KK Nair': 0,
 'AR Patel': 0,
 'LMP Simmons': 0,
 'DJ Hooda': 0,
 'GJ Bailey': 0,
 'AD Russell': 0,
 'MA Agarwal': 0,
 'SS Iyer': 0,
 'MA Starc': 0,
 'VR Aaron': 0,
 'TA Boult': 0,
 'NM Coulter-Nile': 0,
 'EJG Morgan': 0,
 'HH Pandya': 0,
 'MC Henriques': 0,
 'Z Khan': 0,
 'MJ McClenaghan': 0,
 'Q de Kock': 0,
 'Mustafizur Rahman': 0,
 'SA Yadav': 0,
 'AB Dinda': 0,
 'CH Morris': 0,
 'CR Brathwaite': 0,
 'RR Pant': 0,
 'MP Stoinis': 0,
 'A Zampa': 0,
 'KH Pandya': 0,
 'HM Amla': 0,
 'BCJ Cutting': 0,
 'Rashid Khan': 0,
 'N Rana': 0,
 'JJ Bumrah': 0,
 'AJ Tye': 0,
 'BA Stokes': 0,
 'KS Williamson': 0,
 'JC Buttler': 0,
 'LH Ferguson': 0,
 'Mohammed Shami': 0,
 'RA Tripathi': 0,
 'Mohammed Siraj': 0,
 'HV Patel': 0,
 'Washington Sundar': 0,
 'KV Sharma': 0,
 'KL Rahul': 0,
 'SW Billings': 0,
 'JJ Roy': 0,
 'B Stanlake': 0,
 'JC Archer': 0,
 'AS Rajpoot': 0,
 'TG Southee': 0,
 'Mujeeb Ur Rahman': 0,
 'Ishan Kishan': 0,
 'Kuldeep Yadav': 0,
 'S Gopal': 0,
 'L Ngidi': 0,
 'PP Shaw': 0,
 'JM Bairstow': 0,
 'SM Curran': 0,
 'AS Joseph': 0,
 'K Rabada': 0,
 'HF Gurney': 0,
 'DL Chahar': 0,
 'Imran Tahir': 0,
 'KMA Paul': 0,
 'KK Ahmed': 0,
 'Shubman Gill': 0,
 'SO Hetmyer': 0,
 'CV Varun': 0,
 'CJ Jordan': 0,
 'Shivam Mavi': 0,
 'A Nortje': 0,
 'RD Gaikwad': 0,
 'R Tewatia': 0,
 'PK Garg': 0,
 'PJ Cummins': 0}

In [14]:
# Creation of the new Dataset.
for match in tqdm(range(0,len(x))):
    motm=x['player_of_match'].iloc[match]
    for player in players_won:
        if motm==player:
            players_won[player]=players_won[player]+int(1)
            new_x[player].iloc[match]=players_won[player]
        else:
            new_x[player].iloc[match]=players_won[player]

  0%|          | 0/816 [00:00<?, ?it/s]

100%|██████████| 816/816 [00:33<00:00, 24.51it/s]

In [15]:
new_x

,BB McCullum,MEK Hussey,MF Maharoof,MV Boucher,DJ Hussey,SR Watson,V Sehwag,ML Hayden,YK Pathan,KC Sangakkara,...,Shubman Gill,SO Hetmyer,CV Varun,CJ Jordan,Shivam Mavi,A Nortje,RD Gaikwad,R Tewatia,PK Garg,PJ Cummins
date,,,,,,,,,,,,,,,,,,,,,
2008-04-18,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-19,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-19,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-20,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-20,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-28,5.0,12.0,1.0,2.0,2.0,16.0,11.0,4.0,16.0,5.0,...,2.0,1.0,1.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0
2020-11-05,5.0,12.0,1.0,2.0,2.0,16.0,11.0,4.0,16.0,5.0,...,2.0,1.0,1.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0
2020-11-06,5.0,12.0,1.0,2.0,2.0,16.0,11.0,4.0,16.0,5.0,...,2.0,1.0,1.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0
2020-11-08,5.0,12.0,1.0,2.0,2.0,16.0,11.0,4.0,16.0,5.0,...,2.0,1.0,1.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0
2020-11-10,5.0,12.0,1.0,2.0,2.0,16.0,11.0,4.0,16.0,5.0,...,2.0,1.0,1.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0

In [16]:
#Deleting rows with the same date

new_x=new_x.reset_index()
delete_index=[]
for match in tqdm(range(0,len(new_x))):
    try:
        if new_x['date'].iloc[match]==new_x['date'].iloc[match+1]:
            delete_index.append(match)
    except:
        pass

new_x = new_x.drop(new_x.index[delete_index])

  0%|          | 0/816 [00:00<?, ?it/s]

100%|██████████| 816/816 [00:00<00:00, 37984.88it/s]

In [17]:
final_x=new_x.set_index('date')

In [18]:
final_x

,BB McCullum,MEK Hussey,MF Maharoof,MV Boucher,DJ Hussey,SR Watson,V Sehwag,ML Hayden,YK Pathan,KC Sangakkara,...,Shubman Gill,SO Hetmyer,CV Varun,CJ Jordan,Shivam Mavi,A Nortje,RD Gaikwad,R Tewatia,PK Garg,PJ Cummins
date,,,,,,,,,,,,,,,,,,,,,
2008-04-18,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-19,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-20,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-21,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-22,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-28,5.0,12.0,1.0,2.0,2.0,16.0,11.0,4.0,16.0,5.0,...,2.0,1.0,1.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0
2020-11-05,5.0,12.0,1.0,2.0,2.0,16.0,11.0,4.0,16.0,5.0,...,2.0,1.0,1.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0
2020-11-06,5.0,12.0,1.0,2.0,2.0,16.0,11.0,4.0,16.0,5.0,...,2.0,1.0,1.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0
2020-11-08,5.0,12.0,1.0,2.0,2.0,16.0,11.0,4.0,16.0,5.0,...,2.0,1.0,1.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0
2020-11-10,5.0,12.0,1.0,2.0,2.0,16.0,11.0,4.0,16.0,5.0,...,2.0,1.0,1.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0

In [ ]:
bcr.bar_chart_race(
        df=final_x, 
        filename='../docs/images/covid19_horiz.gif', 
        orientation='h', 
        sort='desc', 
        n_bars=8, 
        fixed_order=False, 
        fixed_max=True, 
        steps_per_period=20, 
        period_length=500, 
        end_period_pause=0,
        interpolate_period=False, 
        period_label={'x': .98, 'y': .3, 'ha': 'right', 'va': 'center'}, 
        period_template='%B %d, %Y', 
        period_summary_func=lambda v, r: {'x': .98, 'y': .2, 
                                          's': f'Total deaths: {v.sum():,.0f}', 
                                          'ha': 'right', 'size': 11}, 
        perpendicular_bar_func='median', 
        colors='dark12', 
        title='Toss won over the years', 
        bar_size=.95, 
        bar_textposition='inside',
        bar_texttemplate='{x:,.0f}', 
        bar_label_font=7, 
        tick_label_font=7, 
        tick_template='{x:,.0f}',
        shared_fontdict=None, 
        scale='linear', 
        fig=None, 
        writer=None, 
        bar_kwargs={'alpha': .7},
        fig_kwargs={'figsize': (6, 3.5), 'dpi': 144},
        filter_column_colors=False)

In [14]:
#Toss winners 
x['toss_winner'].value_counts()

toss_winner
Mumbai Indians                 106
Kolkata Knight Riders           98
Chennai Super Kings             97
Royal Challengers Bangalore     87
Rajasthan Royals                87
Kings XI Punjab                 85
Delhi Daredevils                80
Sunrisers Hyderabad             57
Deccan Chargers                 43
Pune Warriors                   20
Delhi Capitals                  20
Gujarat Lions                   15
Kochi Tuskers Kerala             8
Rising Pune Supergiants          7
Rising Pune Supergiant           6
Name: count, dtype: int64

In [15]:
#Getting all the teams into a list
x['toss_winner']=x['toss_winner'].replace("Rising Pune Supergiant","Rising Pune Supergiants")
team_list=list(x['toss_winner'].unique())

In [16]:
#Making a new Dataset which is required for the bar chart race
data=np.zeros((816,14))
new_x=pd.DataFrame(data,index=x['date'],columns=team_list)
new_x

,Royal Challengers Bangalore,Chennai Super Kings,Rajasthan Royals,Mumbai Indians,Deccan Chargers,Kings XI Punjab,Kolkata Knight Riders,Delhi Daredevils,Kochi Tuskers Kerala,Pune Warriors,Sunrisers Hyderabad,Gujarat Lions,Rising Pune Supergiants,Delhi Capitals
date,,,,,,,,,,,,,,
2008-04-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-11-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-11-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-11-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-11-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
# Sample Dictionary which we will use in the new Dataset.
tosses_won={}
for team in team_list:
    tosses_won[team]=0
tosses_won

{'Royal Challengers Bangalore': 0,
 'Chennai Super Kings': 0,
 'Rajasthan Royals': 0,
 'Mumbai Indians': 0,
 'Deccan Chargers': 0,
 'Kings XI Punjab': 0,
 'Kolkata Knight Riders': 0,
 'Delhi Daredevils': 0,
 'Kochi Tuskers Kerala': 0,
 'Pune Warriors': 0,
 'Sunrisers Hyderabad': 0,
 'Gujarat Lions': 0,
 'Rising Pune Supergiants': 0,
 'Delhi Capitals': 0}

In [18]:
# Creation of the new Dataset.
for match in range(0,len(x)):
    tosswon=x['toss_winner'].iloc[match]
    for team in tosses_won:
        if tosswon==team:
            tosses_won[team]=tosses_won[team]+int(1)
            new_x[team].iloc[match]=tosses_won[team]
        else:
            new_x[team].iloc[match]=tosses_won[team]

In [19]:
new_x

,Royal Challengers Bangalore,Chennai Super Kings,Rajasthan Royals,Mumbai Indians,Deccan Chargers,Kings XI Punjab,Kolkata Knight Riders,Delhi Daredevils,Kochi Tuskers Kerala,Pune Warriors,Sunrisers Hyderabad,Gujarat Lions,Rising Pune Supergiants,Delhi Capitals
date,,,,,,,,,,,,,,
2008-04-18,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-19,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-19,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-20,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-20,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-28,87.0,97.0,87.0,106.0,43.0,85.0,98.0,80.0,8.0,20.0,56.0,15.0,13.0,17.0
2020-11-05,87.0,97.0,87.0,106.0,43.0,85.0,98.0,80.0,8.0,20.0,56.0,15.0,13.0,18.0
2020-11-06,87.0,97.0,87.0,106.0,43.0,85.0,98.0,80.0,8.0,20.0,57.0,15.0,13.0,18.0
2020-11-08,87.0,97.0,87.0,106.0,43.0,85.0,98.0,80.0,8.0,20.0,57.0,15.0,13.0,19.0
2020-11-10,87.0,97.0,87.0,106.0,43.0,85.0,98.0,80.0,8.0,20.0,57.0,15.0,13.0,20.0

In [20]:
#Deleting rows with the same date
new_x=new_x.reset_index()
delete_index=[]
for match in range(0,len(new_x)):
    try:
        if new_x['date'].iloc[match]==new_x['date'].iloc[match+1]:
            delete_index.append(match)
    except:
        pass

new_x = new_x.drop(new_x.index[delete_index])

In [21]:
final_x=new_x.set_index('date')
final_x

,Royal Challengers Bangalore,Chennai Super Kings,Rajasthan Royals,Mumbai Indians,Deccan Chargers,Kings XI Punjab,Kolkata Knight Riders,Delhi Daredevils,Kochi Tuskers Kerala,Pune Warriors,Sunrisers Hyderabad,Gujarat Lions,Rising Pune Supergiants,Delhi Capitals
date,,,,,,,,,,,,,,
2008-04-18,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-19,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-20,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-21,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2008-04-22,1.0,1.0,1.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-28,87.0,97.0,87.0,106.0,43.0,85.0,98.0,80.0,8.0,20.0,56.0,15.0,13.0,17.0
2020-11-05,87.0,97.0,87.0,106.0,43.0,85.0,98.0,80.0,8.0,20.0,56.0,15.0,13.0,18.0
2020-11-06,87.0,97.0,87.0,106.0,43.0,85.0,98.0,80.0,8.0,20.0,57.0,15.0,13.0,18.0
2020-11-08,87.0,97.0,87.0,106.0,43.0,85.0,98.0,80.0,8.0,20.0,57.0,15.0,13.0,19.0
2020-11-10,87.0,97.0,87.0,106.0,43.0,85.0,98.0,80.0,8.0,20.0,57.0,15.0,13.0,20.0

In [22]:
import bar_chart_race as bcr
bcr.bar_chart_race(df = final_x, 
                   n_bars = 7, 
                   sort='desc',
                   title='Toss winners of a match since 2008',
                   filename = 'toss_winners.mp4')

MovieWriter ffmpeg unavailable; using Pillow instead.